DATA:
  DATA_NAME: 'Struggle'
  DATA_ROOT: '/media/alexa/WORKSPACE/Shijia-stage-two/new_struggle_dataset'
  DATA_SPLIT_PATH: '/media/alexa/WORKSPACE/Shijia-stage-two/new_struggle_dataset/splits/separate_attempts/Shuffle_Cards/Shuffle_Cards_sepattempt.json'
  TRAIN_SEUBSET: ['train_attempt01', 'train_attempt02', 'train_attempt03', 'train_attempt04', 'train_attempt05']
  TEST_SUBSET: ['validation']
  CLASS_NAMES: ["Background", "Struggle"]
  NUM_CLASSES: 2
  IGNORE_INDEX: -100
  METRICS: 'cAP'
  FPS: 3.125 
INPUT:
  MODALITY: 'twostream'
  VISUAL_FEATURE: 'rgb_slow'
  MOTION_FEATURE: 'flow_fast'
MODEL:
  MODEL_NAME: 'LSTR'
  CHECKPOINT: 'checkpoints/Struggle/LSTR/lstr_anticipation_8sec/separate_attempts-Shuffle_Cards/epoch-20.pth'
  FEATURE_HEAD:
    LINEAR_ENABLED: True
    LINEAR_OUT_FEATURES: 1024
  LSTR:
    NUM_HEADS: 16
    DIM_FEEDFORWARD: 1024
    DROPOUT: 0.2
    ACTIVATION: 'relu'
    LONG_MEMORY_SECONDS: 512
    LONG_MEMORY_SAMPLE_RATE: 4
    WORK_MEMORY_SECONDS: 8
    WORK_MEMORY_SAMPLE_RATE: 1
    ANTICIPATION_SECONDS: 8 # 0 to disable
    ANTICIPATION_SAMPLE_RATE: 1
    ENC_MODULE: [
      [16, 1, True], [32, 2, True]
    ]
    DEC_MODULE: [-1, 2, True]
  CRITERIONS: [['MCE', {}]]
DATA_LOADER:
  BATCH_SIZE: 16
  NUM_WORKERS: 8
  PIN_MEMORY: True
SOLVER:
  NUM_EPOCHS: 20
  OPTIMIZER: 'adam'
  BASE_LR: 1e-6
  WEIGHT_DECAY: 5e-03
  ENABLE_WANDB: True
  PHASES: ['train', 'test']
  SCHEDULER:
    SCHEDULER_NAME: 'warmup_cosine'
    WARMUP_FACTOR: 0.1
    WARMUP_EPOCHS: 5.0
    WARMUP_METHOD: 'linear'




